# Generated by Django 5.2.1 on 2025-05-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_brand_collection_alter_cartitem_options_and_more'),
        ('main', '0008_order'),
    ]

    operations = [
    ]
