# Generated by Django 5.2.1 on 2025-06-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_brand_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
